FROM ubuntu:latest

# RUN apk update
# RUN apk add --no-cache bash
# RUN apk add --no-cache gcompat

RUN mkdir /home/server
WORKDIR /home/server

COPY ./server /home/server/server

EXPOSE 9000
# EXPOSE 9001

CMD ["/home/server/server"]
